version: '3'
services:
  nodejs-server:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: node-api
    restart: unless-stopped
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  angular-ui:
    build:
      context: ./app-ui
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: angular-ui
    restart: unless-stopped
    volumes:
       - ./app-ui:/usr/src/app/app-ui
       - /usr/src/app/app-ui/node_modules